// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:        number;
    paidOrders:            number;
    pendingOrders:         number;
    numberOfClients:       number;
    numberOfProducts:      number;
    productsZero:          number;
    productsByCatNature:   number;
    productsByCatFigure:   number;
    productsByCatAbstract: number;
}
